development:
  baseURL: 'http://local.getperiodic.com/'
  application_settings:
    name: "GetPeriodic - local"
    company: "GetPeriodic"
    company_link: "http://getperiodic.com"
    page_title: "GetPeriodic - Reading is fun"
    info_email: "info@getperiodic.com"
test:
  baseURL: 'https://test.getperiodic.com'
  application_settings:
    name: "GetPeriodic - test"
    company: "GetPeriodic"
    company_link: "http://getperiodic.com"
    page_title: "GetPeriodic - Reading is fun"
    info_email: "info@getperiodic.com"
production:
  baseURL: 'https://getperiodic.com'
  application_settings:
    name: "GetPeriodic"
    company: "GetPeriodic"
    company_link: "http://getperiodic.com"
    page_title: "GetPeriodic - Reading is fun"
    info_email: "info@getperiodic.com"